### ISSUE TITLE
Invalid callback handle

### ISSUE THREAD

**Issue by busterwan** [PeWu/appdaemon-machine#2]
Hi @PeWu:

Your State-Machine library saves me a lot of time in automating a few of my home appliances. Thank you for sharing your hard work. Lately, I encounter the following warning issue. While it is not a deal breaker (the app works fine with the warning), I'm wondering if we can eliminate it by issuing a "cancel_timer" instruction when the sensor becomes "unavailable".

Thank you in advance and much appreciated.

## The issue:

- Encounter WARNING AppDaemon: Invalid callback handle 'cad8ef56e18149d6903d0d50540a56ec' in cancel_timer() from app dishwasher

## Steps to reproduce the issue:

- Add a 'Timeout' transition to a AppDaemon app;
- Power on sensor module (in my case, it is a BH1750 light sensor module attaching to a NodeMCU);
- Create a condition to trigger the timeout and let the timeout transition to run its course;
- Unplug/power off the sensor module;
- Check the AppDaemon log. The said warning shows up.

## My app code:

- App code attached

[dishwasher.txt](https://github.com/PeWu/appdaemon-machine/files/6509027/dishwasher.txt)

**Comment by busterwan** [comment]
Resolved by changing line #137 from
`if self.timer:`
to
`if self.hass.timer_running(self.timer):`

**Comment by PeWu** [comment]
Thanks for finding the solution. I updated the repo with your fix.
